[package]

name = "construct"
version = "0.0.1"
authors = ["Ty Overby <ty@pre-alpha.com>"]
license = "MIT"
repository = "https://github.com/TyOverby/construct"
description = "A macro for building container literals."
